version: '2'
services:
    uranapp-app:
        image: uranapp
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://uranapp-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=uranapp
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    uranapp-mongodb:
        extends:
            file: mongodb.yml
            service: uranapp-mongodb
